//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Quantity { get; set; }
        public int Amount { get; set; }
        public int StatusId { get; set; }
        public System.DateTime TimeOfDelivery { get; set; }
        public int UserId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
